name: actions hello world
on:
  push:
    branches:
    - main
jobs:
  buildContainer:
      runs-on: ubuntu-latest
      steps:
        # - name: Docker Login
        #   uses: docker/login-action@v3.3.0
        #   with:
        #     # Server address of Docker registry. If not set then will default to Docker Hub
        #     registry: git.sethsamuel.online
        #     # Username used to log against the Docker registry
        #     username: fluffy
        #     # Password or personal access token used to log against the Docker registry
        #     password: ${{ secrets.DOCKER_REPO_KEY }}
        #     # Specifies whether the given registry is ECR (auto, true or false)
        #     ecr: # optional, default is auto
        #     # Log out from the Docker registry at the end of a job
        #     logout: true 
        - name: echo hello world
          run: echo "hello world"
          
        - name: echo secret
          run: echo ${{ secret.TEST_SECRET }} 
          
  
