name: actions hello world
on:
  push:
    branches:
    - main
jobs:
  buildContainer:
      runs-on: ubuntu-latest
      environment: SelfHost
      steps:
        - name: Tailscale
          uses: tailscale/github-action@v3
          with:
            authkey: ${{ secrets.TS_KEY }}

        - name: Docker Login
          uses: docker/login-action@v3.3.0
          with:
            # Server address of Docker registry. If not set then will default to Docker Hub
            registry: git.sethsamuel.online
            # Username used to log against the Docker registry
            username: fluffy
            # Password or personal access token used to log against the Docker registry
            password: ${{ secrets.DOCKER_REPO_KEY }}
            # Specifies whether the given registry is ECR (auto, true or false)
            ecr: # optional, default is auto
            # Log out from the Docker registry at the end of a job
            logout: true 
        
        - name: Build and push Docker images
          uses: docker/build-push-action@v6.15.0
          with:
            # Path to the Dockerfile
            file: ./Dockerfile
            # Push is a shorthand for --output=type=registry
            push: true # optional, default is false
            # List of tags
            tags: git.sethsamuel.online/fluffy/mission_ready_mission2

        - name: 'Stack Deploy'
          uses: cssnr/stack-deploy-action@v1
          with:
            name: 'mission_ready_mission2'
            file: 'docker-compose.yaml'
            host: ${{ secrets.DOCKER_HOST }}
            user: ${{ secrets.DOCKER_USER }}
            ssh_key: '${{ secrets.DOCKER_SSH_KEY }}'
